In [154]:
import json

In [4]:
with open('/content/data.json', 'r', encoding='windows-1251') as file:
  data = json.load(file)

In [5]:
data_list = []

In [6]:
for i in data['data']:
  data_list.append([i['Title'], i['Experience'], i['Salary'], i['Region']])

In [7]:
import pandas as pd

In [15]:
df = pd.DataFrame(data_list, columns=data['data'][0].keys())

Перевести ваш спарсенный json в формат csv таблицу через pandas

In [153]:
df.to_csv (r'/content/data_file.csv', index = None)

Сгруппируйте вакансии по направлениями (DS, DE, Software Engenering, etc.)

In [73]:
df.groupby('Title').count()

                                                    Experience  Salary  Region
Title
.Net разработчик / .Net программист (Middle / S...           1       1       1
AI-разработчик junior (удаленно)                             1       1       1
Application Consultant/Консультант-разработчик ...           1       1       1
Application Security Engineer                                1       1       1
Arch Lead                                                    1       1       1
...                                                        ...     ...     ...
Старший системный аналитик                                   1       1       1
Тестировщик / QA (специалист по автотестировани...           2       2       2
Тестировщик ПО                                               1       1       1
Техлид/СТО/Fullstack developer на Python в стартап           1       1       1
Эксперт департамента сертификации и тестирования             1       1       1

[443 rows x 3 columns]

In [84]:
df1 = df.loc[df['Salary'] != 'Не указана']

salary_dict = {}
index = df1.index
count = 0

for i in df1.Salary:
  salary_size = ''

  if 'до ' in i:
    i = i.split('до ')[1]

  if 'USD' in i:
    for j in i.split():
      if j.isdigit():
        salary_size += j
    i = int(salary_size) * 62.65

  else:
    for j in i.split():
      if j.isdigit():
        salary_size += j
    i = salary_size
  
  salary_dict[index[count]] = float(i)
  count += 1

df_salary = pd.DataFrame({'Salary':salary_dict})

Какая средняя и медианная зарплата по группам вакансий?

In [ ]:
df2 = pd.concat([df1['Title'], df_salary], axis=1)

df_out = df2.groupby('Title') ['Salary'].mean()

print(df_out)

df_out = df2.groupby('Title') ['Salary'].median()

print(df_out)

Какая средняя и медианная зарплата по каждому региону?

In [ ]:
df_region_salary = pd.concat([df1['Region'], df_salary], axis=1)

df_out = df_region_salary.groupby('Region') ['Salary'].mean()

print(df_out)

df_out = df_region_salary.groupby('Region') ['Salary'].median()

print(df_out)

Какая самая высокооплачиваемая из групп вакансий, исходя из их средних зарплат?

In [101]:
df_out = df2.groupby('Title') ['Salary'].mean()
print(df_out[df_out == df_out.max()])

Title
Senior Software Engineer    700000.0
Name: Salary, dtype: float64

Какое процентное соотношение каждого региона по вакансиям от всех вакансий?

In [112]:
x = df['Region'].value_counts(normalize=True) * 100
print(round(x, 2), '%', sep='')

Москва                                37.68
Санкт-Петербург                       10.36
Екатеринбург                           2.86
Новосибирск                            2.32
Нижний Новгород                        1.96
                                      ...
Москва, Верхние Котлы и еще 1          0.18
Барнаул                                0.18
Казань, Кремлевская и еще 1            0.18
Санкт-Петербург, Московские ворота     0.18
Муром                                  0.18
Name: Region, Length: 148, dtype: float64%

Какая корреляция уровня опыта от зарплаты?

In [134]:
df1 = df.loc[df['Salary'] != 'Не указана'][df['Experience'] != 'не требуется'][df['Experience'] != 'не указан']
# df1
experience_dict = {}
index = df1.index
exp_count = 0
#experience
df1.Experience
for i in df1.Experience:
  experience_size = ''

  if '–' in i:
    i = i.split('–')[1]

  for j in i.split():
    if j.isdigit():
      experience_size += j
  i = experience_size
  
  experience_dict[index[exp_count]] = int(i)
  exp_count += 1

df_experience = pd.DataFrame({'Experience':experience_dict})
df_experience

#salary
salary_dict = {}
count = 0

for i in df1.Salary:
  salary_size = ''

  if 'до ' in i:
    i = i.split('до ')[1]

  if 'USD' in i:
    for j in i.split():
      if j.isdigit():
        salary_size += j
    i = int(salary_size) * 62.65

  else:
    for j in i.split():
      if j.isdigit():
        salary_size += j
    i = salary_size
  
  salary_dict[index[count]] = float(i)
  count += 1

df_salary = pd.DataFrame({'Salary':salary_dict})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [140]:
df2 = pd.concat([df_experience, df_salary], axis=1)
df2['Experience']. corr(df2['Salary'])

0.3452461111594192

Сколько должностей в наборе данных?

In [145]:
df['Title'].nunique()

443

Какие 10 наиболее часто встречающихся должностей?

In [151]:
df['Title'].value_counts().nlargest(10)

Разработчик Python                13
Python разработчик                11
Python-разработчик                 9
Программист Python                 8
Инженер-программист                8
Middle Python Developer            6
Senior/Lead Python-разработчик     6
Python Developer                   5
Senior Python разработчик          4
Разработчик BI                     4
Name: Title, dtype: int64

Далее код практического занятия

In [ ]:
df = pd.read_csv('/content/train.csv', index_col='PassengerId')

In [ ]:
df

In [ ]:
df.groupby('Survived').count()

In [ ]:
df[df['Survived']==1].count()

In [ ]:
one_percent = df.Survived.count()/100

In [ ]:
survived = df.Survived.sum()
survived

In [ ]:
x = survived/one_percent

In [ ]:
round(x, 2)

In [ ]:
df[df['Pclass'] == 1].Survived.count()

In [ ]:
x = df[df['Pclass'] == 1].Survived.count() * 100 / df.Survived.count()
print(round(x, 2), '%', sep='')

In [ ]:
print(df.Age.mean(), df.Age.median())

In [ ]:
df_2 = pd.DataFrame(df, columns = ['SibSp', 'Parch'])

In [ ]:
df_2.corr().loc['SibSp', 'Parch']

In [ ]:
names = list(df[df['Sex'] == 'female'].Name)

In [ ]:
names

In [ ]:
names = list(df[df['Sex'] == 'female'].Name)

for i in range(len(names)):
  if '(' in names[i]:
    names[i] = names[i].split('(')[1].replace(')', '')
  elif 'Miss.' in names[i]:
    names[i] = names[i].split('Miss. ')[1]
  elif 'Mrs.' in names[i]:
    names[i] = names[i].split('Mrs. ')[1]
  elif 'Ms.' in names[i]:
    names[i] = names[i].split('Ms. ')[1]
  elif 'Mlle.' in names[i]:
    names[i] = names[i].split('Mlle. ')[1]
  elif 'Mme.' in names[i]:
    names[i] = names[i].split('Mme. ')[1]

  if '"' in names[i]:
    names[i] = names[i].replace('"', '')
  print(names[i])

In [ ]:
names_dict = {}
for i in names:
  for j in i.split(' '):
    if j in names_dict:
      names_dict[j] += 1
    else:
      names_dict[j] = 1

In [ ]:
names_dict

In [ ]:
for key, value in names_dict.items():
  if value > 9:
    print(key, value)